#!/usr/bin/env bash
<< 'EOF'
Manipulate a matrix or dataframe given in a CSV file

USAGE:
    ./bmat -t <filename>
    ./bmat < -d | -r | -c > <rows|cols> <filename>

INPUT:
    Dataframe in a CVS file

OUTPUT:
    - The transpose of the dataframe if -t is specified
    - A slice of the original dataframe if -r and/or -c are specified.
    - Option -d is for deleting rows and/or columns.

EXAMPLES:
    echo 'col1,col2,col3,col4,col5,col6,col7,col8,col9,col10' >> ./filecsv
    echo '1,2,3,4,5,6,7,8,9,10'                               >> ./filecsv
    echo '11,12,13,14,15,16,17,18,19,20'                      >> ./filecsv
    echo '21,22,23,24,25,26,27,28,29,30'                      >> ./filecsv

    ./bmat -c 2 filecsv              # select second column
    ./bmat -c 3,1 filecsv            # select third then first column
    ./bmat -c 1-3 filecsv            # select first till third column
    ./bmat -c 4,col2-col3 filecsv    # select fourth column, then columns col2 till col3.
    ./bmat -c 1,3 -r 2- filecsv      # select first and third columns, second till last row
    ./bmat -c 1 -r 2 filecsv         # select an element (first column, second row)
    ./bmat -t filecsv                # transpose
    ./bmat -d -r 1,3 -c 1-5 filecsv  # drop rows 1 and 3 and columns 1 till 5\n"

ADVANCED EXAMPLES:

    # replace in 2nd row, all 1s by 9s
    {
    ./bmat -r 1 filecsv
    ./bmat -r 2 filecsv | sed 's/1/9/g'
    ./bmat -r 3- filecsv
    }

    # replace in 3rd column, all 3s by 9s
    ./bmat -t filecsv > /tmp/filetmp
    {
    ./bmat -r 1-2 /tmp/filetmp
    ./bmat -r 3 /tmp/filetmp | sed 's/3/9/g'
    ./bmat -r 4- /tmp/filetmp
    } > /tmp/filetmp2
    ./bmat -t /tmp/filetmp2

    # replace 1s by 9s overall
    cat filecsv | sed 's/1/9/g'

J.A., ykxvqz@pm.me
EOF

set -eo pipefail

filetmp1=`mktemp "/tmp/${0##*/}.XXX"`
filetmp2=`mktemp "/tmp/${0##*/}.XXXX"`
filetmp3=`mktemp "/tmp/${0##*/}.XXXXX"`
filetmp4=`mktemp "/tmp/${0##*/}.XXXXXX"`

print_usage(){
    echo -e "
    subset selection from a csv file
    
    USAGE:
    ./bmat -c 2 filecsv              # select second column
    ./bmat -c 1,3 filecsv            # select first and third columns
    ./bmat -c 1-3 filecsv            # select first till third column
    ./bmat -c 1,3 -r 2- filecsv      # select first and third columns, second till last row
    ./bmat -c 1 -r 2 filecsv         # select an element (first column, second row)
    ./bmat -t filecsv                # transpose
    ./bmat -d -r 1,3 -c 1-5 filecsv  # drop rows 1 and 3 and columns 1 till 5\n"
}

transpose(){
    local file="$1"
    local n_cols=`head -1 "$file" | tr ',' ' ' | wc -w`
    for i in `seq 1 "$n_cols"`; do
        cut -d ',' -f "$i" "$file" | xargs | tr ' ' ','
    done
}

# e.g. col3,col1,col2-col3 -> 3,1,2-3
str2num() {
    local items="$1"
    local file="$2"

    unset a
    declare -A a
    cnt=1
    for i in `head -1 "$file" | tr ',' ' '`; do
        a["$i"]=$cnt
        ((cnt++))
    done

    for i in `head -1 "$file" | tr ',' ' '`; do
        item=`grep -oE "$i" <<< "$items" | head -1`
        # if non-zero and non-integer
        [ "$item" -eq "$item" ] 2>/dev/null
        if [ "$?" -ne 0 ] && [ -n "$item" ]; then
            val=`echo ${a["$item"]}`
            items=`sed -E "s/$i/$val/g" <<< "$items"`
        fi
    done
    echo "$items"
}

# enumerate input as a,b,c,d,...
enum() {
    local items="$1"
    local max_items="$2"
    for i in `echo "$items" | tr ',' ' '`; do
        if [ -z `grep '-' <<< "$i"` ]; then
            echo "$i"
        else
            # we have a range item (start-end)
            start=`grep -oE '^[^-]*' <<< "$i"`
            end=`grep -oE '[^-]*$' <<< "$i"`
            if [ -z "$start" ]; then
                start=1
            fi
            if [ -z "$end" ]; then
                end="$max_items"
            fi
            seq "$start" "$end"  # null-string if start > end
        fi
    done | xargs | tr ' ' ','
}

col_select(){
    local cols="$1"
    local file="$2"
    local n_cols=`head -1 "$file" | tr ',' ' ' | wc -w`

    if [ "$n_cols" -eq 1 ] &&
       [[ ! "$cols" =~ ^1- ]] &&
       [[ ! "$cols" =~ -1$ ]] &&
       [[ ! "$cols" =~ ^1, ]] &&
       [[ ! "$cols" =~ ,1, ]] &&
       [[ ! "$cols" =~ ,1$ ]] &&
       [[ ! "$cols" =~ ^1$ ]]; then
        echo ''
    else
        cols=`str2num "$cols" "$file"`
        cols=`enum "$cols" "$n_cols"`
        # cut 1 column at a time to preserve desired order
        for i in `echo "$cols" | tr ',' ' '`; do
            cut -d ',' -f "$i" "$file" | xargs | tr ' ' ','
        done > "$filetmp1"
        transpose "$filetmp1"
    fi
}

row_select() {
    local rows="$1"
    local file="$2"
    transpose "$file" > "$filetmp2"
    col_select "$rows" "$filetmp2" > "$filetmp3"
    transpose "$filetmp3"
}

col_deselect(){
    local cols="$1"
    local file="$2"
    local n_cols=`head -1 "$file" | tr ',' ' ' | wc -w`

    if [ "$n_cols" -eq 1 ] && (
       [[ "$cols" =~ ^1- ]] ||
       [[ "$cols" =~ -1$ ]] ||
       [[ "$cols" =~ ^1, ]] ||
       [[ "$cols" =~ ,1, ]] ||
       [[ "$cols" =~ ,1$ ]] ||
       [[ "$cols" =~ ^1$ ]] ); then
        echo ''
    else
        cols=`str2num "$cols" "$file"`
        cut --complement -d ',' -f "$cols" "$file"
    fi
}

row_deselect() {
    local rows="$1"
    local file="$2"
    transpose "$file" > "$filetmp2"
    col_deselect "$rows" "$filetmp2" > "$filetmp3"
    transpose "$filetmp3"
}

main(){

    while getopts 'hc:r:td' option; do
        case $option in
            h ) print_usage; exit 0;;
            c ) col="$OPTARG";;
            r ) row="$OPTARG";;
	        t ) flip='true';;
	        d ) drop='true';; 
            -*) echo 'Unknown option. Exiting ...'; exit 1;;
        esac
    done

    argf="${@: -1}"
    if [ "$argf" != '-h' -a \
         "$argf" != '-r' -a \
         "$argf" != '-c' -a \
         "$argf" != '-t' -a \
         "$argf" != '-d' -a \
         "$argf" != "$0" ]; then
        filecsv="$argf"
    else
        echo 'No file specified!'
        exit 1
    fi

    # transpose
    if [ "$flip" == 'true' ]; then
        if [ -n "$col" ] || [ -n "$row" ] || [ -n "$drop" ]; then
            echo 'Cannot use other options when option -t is set!'
            print_usage
            exit 1
        else
            transpose "$filecsv"
            exit 0
        fi
    fi

    if [ -z "$drop" ]; then
        # row select
        if [ -z "$col" ] && [ -n "$row" ]; then
            row_select "$row" "$filecsv"
        fi
        # column select
        if [ -z "$row" ] && [ -n "$col" ]; then
            col_select "$col" "$filecsv"
        fi
        # row and column select
        if [ -n "$col" ] && [ -n "$row" ]; then
            col_select "$col" "$filecsv" > "$filetmp4"
            row_select "$row" "$filetmp4"
        fi
    else
        # row deselect
        if [ -z "$col" ] && [ -n "$row" ]; then
             row_deselect "$row" "$filecsv"
        fi
        # column deselect
        if [ -z "$row" ] && [ -n "$col" ]; then
            col_deselect "$col" "$filecsv"
        fi
        # row and column deselect
        if [ -n "$col" ] && [ -n "$row" ]; then
            col_deselect "$col" "$filecsv" >> "$filetmp4"
            row_deselect "$row" "$filetmp4"
        fi
    fi
    rm "$filetmp1" "$filetmp2" "$filetmp3" "$filetmp4"
}

main "$@"
