#!/usr/bin/env bash
: '
Create line breaks in a document at a limit of 72 characters without breaking any words.

Usage:  ./linecutter file

ARGS:
        file: an ASCII text file

OUTPUT:
        file: the original file is overwritten to the current directory;
              create a copy first if you wish to keep the original file.

DESCRIPTION:

If a line happens to extend beyond 72 characters, a newline character is
added at a position that is lower but closest to the 72nd character in
such a way as not to break any words. Internals of the method are
described below:

1. Append a marker string to the file so that line-by-line processing
stops when the marker is reached, allowing the script to end.
2. Starting with the first line of the document, if the length of the
line is greater than 72 characters, then the maximum-length pattern
consisting of at most 72 characters followed by whitespace will be
replaced by the 72 characters plus a newline appended. The file has now
increased by 1 line, and the result is saved in-place within the file.
3. The line counter is incremented, and the previous condition is
checked again for the next line. This is repeated line-by-line until
the end-of-file marker is reached.
4. The last line of the document (containing the marker) is then removed.

Why 72 characters? Because it ensures readability on most screens, and
Geany editor has a screen split at 72 characters. Note: linecutter will
not do anything special to lines that originally contain indentations.

EXAMPLE:

Below is some sample text of the input file, and the resulting output.

Input:

Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum. 

Output:

Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod
tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam,
nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit
in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui
officia deserunt mollit anim id est laborum.

J.A., xrzfyvqk_k1jw@pm.me
'

USAGE="Usage: $0 [file]"

if [ "$#" == "0" ]; then
    echo "$USAGE"
    exit 1
fi

file="$1"

marker='!EOF'
echo "$marker" >> "$file"

i=1
while [ "$(head -n $i "$file" | tail -1)" != "$marker" ]; do
    if [ $(sed -n "$i p" "$file" | wc -c) -gt 72 ]; then
        sed -i "$i s/^\(.\{0,72\}\)\s/\1\n/" "$file"
    fi
    let i+=1
done

sed -i '$d' "$file"
