#!/usr/bin/env bash
: '
Find dimensions of a dataframe in a CSV file

USAGE:  ./shape [ -r | -c ] <filename>

ARGS:
        input file: CSV file

OUTPUT:
        n_rows n_cols: if no option is set.
	n_rows: if -r is set.
	n_cols: if -c is set.
	
EXAMPLES:
        echo '1,2,3,4,5,6,7,8,9,10'          >> ./filecsv
        echo '11,12,13,14,15,16,17,18,19,20' >> ./filecsv
        echo '21,22,23,24,25,26,27,28,29,30' >> ./filecsv

	./shape filecsv       # number of rows and columns
        ./shape -r filecsv    # number of rows only
        ./shape -c filecsv    # number of columns only\n"

J.A., ykxvqz@pm.me
'

set -eo pipefail

print_usage(){
    echo -e "
    Get shape (rows, columns) of a csv file.

    USAGE:
    ./shape filecsv       # number of rows and columns
    ./shape -r filecsv    # number of rows only
    ./shape -c filecsv    # number of columns only\n"
}

while getopts 'hrc' option; do
    case "$option" in
        h ) print_usage; exit 0;;
        r ) rows='true';;
        c ) cols='true';;
        -*) echo 'Unknown option. Exiting...'; exit 1;;
    esac
done

argf="${@: -1}"

if [ "$argf" != '-h' -a \
     "$argf" != '-r' -a \
     "$argf" != '-c' -a \
     "$argf" != "$0" ]; then
    filecsv="$argf"
else
    echo 'No file specified!'
    exit 1
fi

n_cols=`head -1 "$filecsv" | tr ',' ' ' | wc -w`
n_rows=`cat "$filecsv" | wc -l`

if [ -z "$rows" ] && [ -z "$cols" ]; then
    echo "$n_rows" "$n_cols"
elif [ "$rows" == "true" ]; then
    echo "$n_rows"
elif [ "$cols" == "true" ]; then
    echo "$n_cols"
fi

