#!/usr/bin/env bash
<< 'EOF'
Slice subsets of a matrix or dataframe given in a CSV file

USAGE:
    ./subset [ -t <filename> ] | [[ -d ] | [ -r | -c ]] <rows|cols> <filename>

INPUT:
    Dataframe in a CVS file

OUTPUT:
    - The transpose of the dataframe if -t is specified
    - A slice of the original dataframe if -r and/or -c are specified.
    - Option -d is for deleting rows and/or columns.

EXAMPLES:
    echo '1,2,3,4,5,6,7,8,9,10'          >> ./filecsv
    echo '11,12,13,14,15,16,17,18,19,20' >> ./filecsv
    echo '21,22,23,24,25,26,27,28,29,30' >> ./filecsv

    ./subset -c 2 filecsv              # select second column
    ./subset -c 1,3 filecsv            # select first and third column
    ./subset -c 1-3 filecsv            # select first till third column
    ./subset -c 1,3 -r 2- filecsv      # select first and third column, second till last row
    ./subset -c 1 -r 2 filecsv         # select an element (first column, second row)
    ./subset -t filecsv                # transpose
    ./subset -d -r 1,3 -c 1-5 filecsv  # drop rows 1 and 3 and columns 1 till 5\n"

ADVANCED EXAMPLES:

    # replace in 2nd row, all 1s by 9s
    ./subset -r 1 filecsv
    ./subset -r 2 filecsv | sed 's/1/9/g'
    ./subset -r 3- filecsv

    # replace in 3rd column, all 3s by 9s
    ./subset -t filecsv > /tmp/filetmp

    {
    ./subset -r 1-2 /tmp/filetmp
    ./subset -r 3 /tmp/filetmp | sed 's/3/9/g'
    ./subset -r 4- /tmp/filetmp
    } > /tmp/filetmp2

    ./subset -t /tmp/filetmp2

    # replace 1s by 9s overall
    cat filecsv | sed 's/1/9/g'

J.A., ykxvqz@pm.me
EOF

set -eo pipefail

filetmp1=`mktemp "/tmp/${0##*/}.XXX"`
filetmp2=`mktemp "/tmp/${0##*/}.XXXXXX"`

print_usage(){
    echo -e "
    subset selection from a csv file
    
    USAGE:
    ./subset -c 2 filecsv              # select second column
    ./subset -c 1,3 filecsv            # select first and third column
    ./subset -c 1-3 filecsv            # select first till third column
    ./subset -c 1,3 -r 2- filecsv      # select first and third column, second till last row
    ./subset -c 1 -r 2 filecsv         # select an element (first column, second row)
    ./subset -t filecsv                # transpose
    ./subset -d -r 1,3 -c 1-5 filecsv  # drop rows 1 and 3 and columns 1 till 5\n"
}

transpose(){
    local file="$1"
    n_cols=`head -1 "$file" | tr ',' ' ' | wc -w`
    for i in `seq 1 "$n_cols"`; do
        cut -d ',' -f "$i" "$file" | xargs | tr ' ' ','
    done
}

row_select(){
    local rows="$1"
    local file="$2"

    # transpose and cut
    transpose "$file" | cut -d ',' -f "$rows" > "$filetmp1"

    # re-transppse
    transpose "$filetmp1"
}

row_deselect(){
    local rows="$1"
    local file="$2"

    # transpose and cut
    transpose "$file" | cut --complement -d ',' -f "$rows" > "$filetmp1"

    # re-transppse
    transpose "$filetmp1"
}

main(){

    while getopts 'hc:r:td' option; do
        case $option in
            h ) print_usage; exit 0;;
            c ) col="$OPTARG";;
            r ) row="$OPTARG";;
	    t ) flip='true';;
	    d ) drop='true';; 
            -*) echo 'Unknown option. Exiting ...'; exit 1;;
        esac
    done

    argf="${@: -1}"
    if [ "$argf" != '-h' -a \
         "$argf" != '-r' -a \
         "$argf" != '-c' -a \
	 "$argf" != '-t' -a \
	 "$argf" != '-d' -a \
         "$argf" != "$0" ]; then
        filecsv="$argf"
    else
        echo 'No file specified!'
        exit 1
    fi

    # transpose
    if [ "$flip" == 'true' ]; then
        transpose "$filecsv"
        exit 0
    fi

    if [ -z "$drop" ]; then
        # row select
        if [ -z "$col" ] && [ -n "$row" ]; then
            row_select "$row" "$filecsv"
        fi
        # column select
        if [ -z "$row" ] && [ -n "$col" ]; then
            cut -d ',' -f "$col" "$filecsv"
        fi
        # row and column select
        if [ -n "$col" ] && [ -n "$row" ]; then
            cut -d ',' -f "$col" "$filecsv" > "$filetmp2"
            row_select "$row" "$filetmp2"
        fi
    else
        # row deselect
        if [ -z "$col" ] && [ -n "$row" ]; then
             row_deselect "$row" "$filecsv"
        fi
        # column deselect
        if [ -z "$row" ] && [ -n "$col" ]; then
            cut --complement -d ',' -f "$col" "$filecsv"
        fi
        # row and column deselect
        if [ -n "$col" ] && [ -n "$row" ]; then
            cut --complement -d ',' -f "$col" "$filecsv" > "$filetmp2"
            row_deselect "$row" "$filetmp2"
        fi
    fi
}

main "$@"
