#!/usr/bin/env bash

<< 'EOF'
Add an element to a CSV list

USAGE:
    ./add <-i index> <-d data> <CSV list>

OUTPUT:
    - A CSV list that include an additional element added at the specified index
    - Note: index count starts at 1

EXAMPLES:
    ./add -i 2 -d 99 1,2,3,4,5           # result: 1,99,2,3,4,5
    echo 1,2,3,4,5 | ./add -i 2 -d 99    # result: 1,99,2,3,4,5
EOF

__print_usage     () { :; }
__add             () { :; }
__parse_arguments () { :; }
__check_arguments () { :; }
__check_index     () { :; }
__apply_add       () { :; }
__main            () { :; }

__print_usage() {
    echo -e "Add an element to a csv list.

    USAGE:
          ./add -i 2 -d 99 1,2,3,4,5
          echo 1,2,3,4,5 | ./add -i 2 -d 99 \n"
}

__add() {
<< 'EOF'
    # index: integer
    # data : single value
    # list : csv list
EOF
    index="${1}"
    data="${2}"
    list="${3}"

    OFS="${IFS}"
    IFS=','
    arr=($list)

    i="$((index-1))"
    x=("${arr[@]::$i}" "$data" "${arr[@]:$i}")

    for i in "${x[@]}"; do
        echo -n "${i},"
    done | rev | cut -c 2- | rev

    IFS="${OFS}"
}

__parse_arguments() {
    args=()
    while [ "$#" -gt 0 ]; do
        case "${1}" in
            -h ) __print_usage; exit 0;;
            -i ) index="${2}"; shift; shift ;;
            -d ) data="${2}"; shift; shift ;;
            -* ) echo "Invalid option ${1}. Exiting ..."; exit 1;;
             * ) args+=("${1}"); shift;;
        esac
    done
}

__check_arguments() {
    if [ -z "${index}" -o -z "${data}" ]; then
        echo 'Incomplete input provided.'
        exit 1 
    fi

    if [[ ! "${index}" =~ ^[1-9][0-9]*$ ]]; then
        echo 'Index should be an integer.'
        exit 1
    fi

    if [ "$(echo "${data}" | wc -l)" -ne 1 ]; then
        echo 'Data can only be one element.'
        exit 1
    fi

    argf="${args[0]}"
    if [ -n "${argf}" ]; then
        f="$(echo "${argf}")"
    else
        f="$(</dev/stdin)"
    fi
}

__check_index() {
    n_list="$(echo "${f}" | tr ',' '\n' | wc -l)"
    if [ "${index}" -lt 1 -o "${index}" -gt "$((n_list+1))" ]; then
        echo 'Index outside range!'
        exit 1
    fi
}

__apply_add() {
    __add "${index}" "${data}" "${f}"
}

__main() {
    __parse_arguments "$@"
    __check_arguments
    __check_index
    __apply_add
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    __main "$@"
fi
