#!/usr/bin/env bash

<< 'EOF'
Slice a CSV data frame

USAGE:
    ./slice <-c column_list | -r row_list> <file>

INPUT:
    CSV data in a file, or via stdin

OUTPUT:
    - A slice of the original CSV data based on -r and/or -c options

EXAMPLES:
    echo col{1..10} | tr ' ' ',' >> file.csv
    echo {1..10}    | tr ' ' ',' >> file.csv
    echo {11..20}   | tr ' ' ',' >> file.csv
    echo {21..30}   | tr ' ' ',' >> file.csv

    ./slice -c 2 file.csv              # select second column
    ./slice -c 3,1 file.csv            # select third column then first column
    ./slice -c 1-3 file.csv            # select first till third column
    ./slice -c 3-1 file.csv            # select third column back till first
    ./slice -c 4,col2-col3 file.csv    # select fourth column, then columns col2 till col3.
    ./slice -c 1,3 -r 2- file.csv      # select first and third columns, second till last row
    ./slice -c 1 -r 2 file.csv         # select an element (first column, second row)
EOF

__print_usage              () { :; }
__source_utility_functions () { :; }
__select_col               () { :; }
__select_row               () { :; }
__parse_arguments          () { :; }
__check_arguments          () { :; }
__check_csv_format         () { :; }
__apply_select             () { :; }
__main                     () { :; }

__print_usage() {
    echo -e "Slice a CSV file.

    USAGE:
        ./slice -c 2 file.csv              # select second column
        ./slice -c 1,3 file.csv            # select first and third columns
        ./slice -c 1-3 file.csv            # select first till third column
        ./slice -c 1,3 -r 2- file.csv      # select first and third columns, second till last row
        ./slice -c 1 -r 2 file.csv         # select an element (first column, second row)
        ./slice -c 4,col2-col3 file.csv    # select fourth column, then columns col2 till col3 \n"
}

__source_utility_functions() {
    src_dir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
    source "${src_dir}/utils.sh"

    transpose="${src_dir}/transpose"
    checkcsv="${src_dir}/checkcsv"
}

__select_col() {
<< 'EOF'
    # col_list: csv string
    # f       : string containing file content or stdin content
EOF
    local col_list="${1}"
    local f="${2}"

    n_col="$(echo "${f}" | head -1 | tr ',' '\n' | wc -l)"
    header="$(echo "${f}" | head -1)"

    col_list="$(__str2num "${col_list}" "${header}")"
    col_list="$(__enumerate "${col_list}" "${n_col}")"

    # check that all numbers are in range
    for i in $(echo "${col_list}" | tr ',' ' '); do
        if [ "$i" -gt "${n_col}" ]; then
            echo 'Invalid input'
            return 1
        fi
    done

    # cut one column at a time to preserve desired order
    for i in $(echo "${col_list}" | tr ',' ' '); do
        echo "${f}" | cut -d ',' -f "$i" | tr '\n' ',' | rev | cut -c 2- | rev
    done | "${transpose}"
}

__select_row() {
<< 'EOF'
    # row_list: csv string
    # f       : string containing file content or stdin content
EOF
    local row_list="${1}"
    local f="${2}"

    f_temp="$(echo "${f}" | "${transpose}")"
    __select_col "${row_list}" "${f_temp}" | "${transpose}"
}

__parse_arguments() {
    args=()
    while [ "$#" -gt 0 ]; do
        case "${1}" in
            -h ) __print_usage; exit 0;;
            -c ) col_list="${2}"; shift; shift ;;
            -r ) row_list="${2}"; shift; shift ;;
            -* ) echo "Unknown option ${1}. Exiting ..."; exit 1;;
             * ) args+=("${1}"); shift;;
        esac
    done
}

__check_arguments() {
    if [ -z "${col_list}" -a -z "${row_list}" ]; then
        echo 'No row(s) or column(s) provided!'
        exit 1
    fi

    argf="${args[0]}"
    if [ -n "${argf}" ]; then
        f="$(cat "${argf}")"
    else
        f="$(</dev/stdin)"
    fi
}

__check_csv_format() {
    echo "${f}" | "${checkcsv}" || exit 1
}

__apply_select() {
    # row select
    if [ -z "${col_list}" -a -n "${row_list}" ]; then
        __select_row "${row_list}" "${f}"
    fi

    # column select
    if [ -z "${row_list}" -a -n "${col_list}" ]; then
        __select_col "${col_list}" "${f}"
    fi

    # row and column select
    if [ -n "${col_list}" ] && [ -n "${row_list}" ]; then
        f_temp="$(__select_col "${col_list}" "${f}")"
        __select_row "${row_list}" "${f_temp}"
    fi
}

__main() {
    __source_utility_functions
    __parse_arguments "$@"
    __check_arguments
    __check_csv_format
    __apply_select
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    __main "$@"
fi
