#!/usr/bin/env bash
<< 'EOF'
Delete an element from a CSV list

USAGE:
    ./delete <-i index> <CSV list>

OUTPUT:
    - A CSV list that excludes the element at the specified index
    - Note: index count starts at 1

EXAMPLES:
    ./delete -i 2 1,2,3,4,5           # result: 1,3,4,5
    echo 1,2,3,4,5 | ./delete -i 2    # result: 1,3,4,5

EOF

#
# print usage
#

print_usage() {
    echo -e "
    Delete an element from a CSV list

    USAGE:

        ./delete -i 2 1,2,3,4,5
        echo 1,2,3,4,5 | ./delete -i 2 \n"
}

#
# delete an element
#

del() {
    # index: integer
    # list : csv list
    index="${1}"
    list="${2}"

    OFS="${IFS}"
    IFS=','
    arr=($list)

    i="$((index-1))"
    unset arr["$i"]

    for i in "${arr[@]}"; do
        echo -n "${i},"
    done | rev | cut -c 2- | rev

    IFS="${OFS}"
}

#
# main()
#

main() {
    args=()
    while [ "$#" -gt 0 ]; do
        case "${1}" in
            -h ) print_usage; exit 0;;
            -i ) index="${2}"; shift; shift ;;
            -* ) echo "Unknown option ${1}. Exiting ..."; exit 1;;
             * ) args+=("${1}"); shift;;
        esac
    done

    if [ -z "$index" ]; then
        echo 'Index not provided!'
        return 1 
    fi

    if [[ ! "${index}" =~ ^[1-9][0-9]*$ ]]; then
        echo 'Index should be an integer.'
        return
    fi

    argf="${args[0]}"
    if [ -n "${argf}" ]; then
        f="$(echo "${argf}")"
    else
        f="$(</dev/stdin)"
    fi

    n_list="$(echo "${f}" | tr ',' '\n' | wc -l)"
    if [ "${index}" -lt 1 -o "${index}" -gt "${n_list}" ]; then
        echo 'Index out of range!'
        return 1
    fi

    del "${index}" "${f}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi

