#!/usr/bin/env bash
<< 'EOF'
Insert a row or column to CSV data

USAGE:
    ins [-c column_list | -r row_list] [file]

INPUT:
    - A CSV data frame in a file, or via stdin

OUTPUT:
    - The original data frame with additional row or column added

EXAMPLES:
    echo 'col1,col2,col3,col4,col5,col6,col7,col8,col9,col10' >> file.csv
    echo '1,2,3,4,5,6,7,8,9,10'                               >> file.csv
    echo '11,12,13,14,15,16,17,18,19,20'                      >> file.csv
    echo '21,22,23,24,25,26,27,28,29,30'                      >> file.csv

    ins -c col11,11,21,31 file.csv    # add a column of data

J.A., ykxvqz@pm.me
EOF

#
# locate script dependencies
#

src_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src_dir="$(readlink -f "$src_dir/ins")"
src_dir=$(dirname "$src_dir")
tp="${src_dir}/tp"

#
# print usage
#

print_usage(){
    echo -e "
    insert a row or a column data to a csv file

    USAGE:

        ins -r 31,32,33,34,35,36,37,38,39,40 file.csv
        ins -c col11,11,21,31 file.csv \n"
}

#
# insert a row
#

ins_row() {
    # data_csv: csv list
    # f       : string containing file content or stdin content
    local data_csv="${1}"
    local f="${2}"

    # check number of items
    n_col=$(echo "${f}" | head -1 | tr ',' '\n' | wc -l)
    n_data=$(echo "${data_csv}" | tr ',' '\n' | wc -l)

    if [ "${n_data}" -ne "${n_col}" ]; then
        echo 'invalid number of elements'
        return 1
    fi

    {
    echo "${f}"
    echo "${data_csv}"
    }
}

#
# insert a column
#

ins_col() {
    # data_csv: csv list
    # f       : string containing file content or stdin content
    local data_csv="${1}"
    local f="${2}"

    # check number of items
    n_row=$(echo "${f}" | "${tp}" | head -1 | tr ',' '\n' | wc -l)
    n_data=$(echo "${data_csv}" | tr ',' '\n' | wc -l)

    if [ "${n_data}" -ne "${n_row}" ]; then
        echo 'Invalid number of elements'
        return 1
    fi

    {
    echo "${f}" | "${tp}"
    echo "${data_csv}"
    } | "${tp}"
}

#
# main()
#

main() {
    args=()
    while [ "$#" -gt 0 ]; do
        case "${1}" in
            -h ) print_usage; exit 0;;
            -c ) col_data="${2}"; shift; shift ;;
            -r ) row_data="${2}"; shift; shift ;;
            -* ) echo "Unknown option ${1}. Exiting ..."; exit 1;;
             * ) args+=("${1}"); shift;;
        esac
    done

    if [ -z "${col_data}" -a -z "${row_data}" ]; then
        echo 'No data provided!'
        return 1
    fi

    argf="${args[0]}"
    if [ -n "${argf}" ]; then
        f="$(cat "${argf}")"
    else
        f="$(</dev/stdin)"
    fi

    if [ -z "$col_data" -a -n "$row_data" ]; then
        ins_row "$row_data" "$f"
    elif [ -z "$row_data" -a -n "$col_data" ]; then
        ins_col "$col_data" "$f"
    elif [ -z "$col_data" -a -z "$row_data" ]; then
        echo 'no input provided'
        return 1
    else
        echo 'provide either row or column data, not both'
        return 1
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
