#!/usr/bin/env bash
<< 'EOF'
Slice a CSV data frame

USAGE:
    sl [-c column_list ] [-r row_list] [file]

INPUT:
    A CSV data frame in a file, or via stdin

OUTPUT:
    - A slice of the original data frame based on -r and/or -c options

EXAMPLES:
    echo 'col1,col2,col3,col4,col5,col6,col7,col8,col9,col10' >> file.csv
    echo '1,2,3,4,5,6,7,8,9,10'                               >> file.csv
    echo '11,12,13,14,15,16,17,18,19,20'                      >> file.csv
    echo '21,22,23,24,25,26,27,28,29,30'                      >> file.csv

    sl -c 2 file.csv              # select second column
    sl -c 3,1 file.csv            # select third then first column
    sl -c 1-3 file.csv            # select first till third column
    sl -c 3-1 file.csv            # select third column back till first
    sl -c 4,col2-col3 file.csv    # select fourth column, then columns col2 till col3.
    sl -c 1,3 -r 2- file.csv      # select first and third columns, second till last row
    sl -c 1 -r 2 file.csv         # select an element (first column, second row)

J.A., ykxvqz@pm.me
EOF

print_usage(){
    echo -e "
    subset slicing a csv file

    USAGE:

        sl -c 2 file.csv              # select second column
        sl -c 1,3 file.csv            # select first and third columns
        sl -c 1-3 file.csv            # select first till third column
        sl -c 1,3 -r 2- file.csv      # select first and third columns, second till last row
        sl -c 1 -r 2 file.csv         # select an element (first column, second row)
        sl -c 4,col2-col3 file.csv    # select fourth column, then columns col2 till col3 \n"
}

#
# source utility functions
#

src_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src_dir="$(readlink -f "$src_dir/sl")"
src_dir=$(dirname "$src_dir")
. "${src_dir}/utils.sh"

#
# select columns
#

select_col() {
    # col_list: csv string
    # f       : string containing file content or stdin content
    local col_list="${1}"
    local f="${2}"

    n_col="$(echo "${f}" | head -1 | tr ',' '\n' | wc -l)"
    header="$(echo "${f}" | head -1)"

    col_list="$(str2num "${col_list}" "${header}")"
    col_list="$(enumerate "${col_list}" "${n_col}")"

    # check that all numbers are in range
    for i in $(echo "${col_list}" | tr ',' ' '); do
        if [ "$i" -gt "${n_col}" ]; then
            echo 'invalid input'
            return 1
        fi
    done

    # cut one column at a time to preserve desired order
    for i in $(echo "${col_list}" | tr ',' ' '); do
        echo "${f}" | cut -d ',' -f "$i" | tr '\n' ',' | rev | cut -c 2- | rev
    done | tp
}

#
# select rows
#

select_row() {
    # row_list: csv string
    # f       : string containing file content or stdin content
    local row_list="${1}"
    local f="${2}"

    f_temp="$(echo "${f}" | tp)"
    select_col "${row_list}" "${f_temp}" | tp
}

main() {
    args=()
    while [ "$#" -gt 0 ]; do
        case "${1}" in
            -h ) print_usage; exit 0;;
            -c ) col_list="${2}"; shift; shift ;;
            -r ) row_list="${2}"; shift; shift ;;
            -* ) echo "Unknown option ${1}. Exiting ..."; exit 1;;
             * ) args+=("${1}"); shift;;
        esac
    done

    if [ -z "${col_list}" -a -z "${row_list}" ]; then
        echo 'No row(s) or column(s) provided!'
        return 1
    fi

    argf="${args[0]}"
    if [ -n "${argf}" ]; then
        f="$(cat "${argf}")"
    else
        f="$(</dev/stdin)"
    fi

    # row select
    if [ -z "${col_list}" -a -n "${row_list}" ]; then
        select_row "${row_list}" "${f}"
    fi

    # column select
    if [ -z "${row_list}" -a -n "${col_list}" ]; then
        select_col "${col_list}" "${f}"
    fi

    # row and column select
    if [ -n "${col_list}" ] && [ -n "${row_list}" ]; then
        f_temp="$(select_col "${col_list}" "${f}")"
        select_row "${row_list}" "${f_temp}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
