#!/usr/bin/env bash
<< 'EOF'
Transpose a CSV data frame

USAGE:
    tp file.csv
    cat file.csv | tp

INPUT:
    - CSV file or input piped via stdin

OUTPUT:
    - Transposed data

EXAMPLES:
    echo 'col1,col2,col3,col4,col5,col6,col7,col8,col9,col10' >> file.csv
    echo '1,2,3,4,5,6,7,8,9,10'                               >> file.csv
    echo '11,12,13,14,15,16,17,18,19,20'                      >> file.csv
    echo '21,22,23,24,25,26,27,28,29,30'                      >> file.csv

    tp file.csv
    cat file.csv | tp

J.A., ykxvqz@pm.me
EOF

#
# print usage
#

print_usage(){
    echo -e "
    transpose csv input

    USAGE:
    
        tp file.csv
        cat file.csv | tp \n"
}

#
# transpose csv content
#

transpose() {
    # f: string containing file content or stdin content
    local f="${1}"

    n_col=$(echo "$f" | head -1 | tr ',' '\n' | wc -l)
    for i in $(seq 1 "${n_col}"); do
        echo "${f}" | cut -d ',' -f "$i" | tr '\n' ',' | rev | cut -c 2- | rev 
    done
}

#
# main()
#

main() {
    while getopts 'h' option; do
        case $option in
            h) print_usage; exit 0;;
            *) echo 'Unknown option. Exiting ...'; exit 1;;
        esac
    done

    argf="${1}"
    if [ -n "${argf}" ]; then
        f="$(cat "${argf}")"
    else
        f="$(</dev/stdin)"
    fi

    transpose "${f}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
